apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: harbor.synthlane.com/library/myapp:1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
